name: gallopgate
description: "Equestrian Center Management System"

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.4.7

  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1

  # DI
  get_it: ^7.6.4

  # FIREBASE
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_storage: ^11.5.6
  cloud_firestore: ^4.13.6

  # State
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # JSON SERIALIZATION
  json_annotation: ^4.8.1

  # UID GENERATION
  uuid: ^4.2.2

  # APP ROUTING
  go_router: ^13.0.1

  # UI
  flutter_speed_dial: ^7.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo/png/
    - assets/fonts/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf
