name: gallopgate
description: "Equestrian Center Management System"

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  build_runner: ^2.4.9

  flutter_native_splash: ^2.3.2
  smooth_page_indicator: ^1.1.0
  iconsax: ^0.0.8
  # Localization

  intl: ^0.19.0

  # DI
  get_it: ^7.6.7

  # Supabase
  supabase_flutter: ^2.5.3

  # State
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # JSON SERIALIZATION
  json_serializable: ^6.8.0

  # UID GENERATION
  uuid: ^4.3.3

  # APP ROUTING
  go_router: ^13.2.2

  # UI
  flutter_speed_dial: ^7.0.0
  table_calendar: ^3.1.1
  modal_bottom_sheet: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  
  flutter_lints: ^3.0.2

flutter_launcher_icons:
  image_path: "assets/images/logo/png/logo_light.png"
  android: "launcher_icon"
  ios: true
  web:
    generate: true
  windows:
    generate: true
  macos:
    generate: true

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/logo/png/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-Light.ttf

    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik-Light.ttf
